language: ruby
loglevel: debug
git:
  username: user
  token: agithubpersonaltoken
webhook:
  secret: asupersecretkey
ruby:
  authors: somepeople
  email: dev@dev.com
  gemrepouser: user
  gemrepopass: pass
  gemrepohost: https://somegemrepo.com
  gemname: proto-demo
  grpcversion: '1.19.0'
  homepage: https://github.com/someorg/somerepo
  publish: false
scala:
  description: Proto gen files for company x
  mavenrepopublishtarget: https://somejarrepo/maven
  jarname: proto-demo
  organization: company x
  publish: false
  realm: PrivateRepoProduct
  sbtversion: '1.5.5'
  currentScalaVersion: '2.12.10'
  legacyScalaVersion: '2.11.12'
  sbtprotocpluginpackageversion: '0.99.33'
  scalapbtruntimepackageversion: '0.10.0-M4'
