// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.demo.bifrost.token.v1.token

/** APIKey contains the necessary information about an api key.
  */
@SerialVersionUID(0L)
final case class APIKey(
    token: _root_.scala.Predef.String = "",
    companyId: _root_.scala.Long = 0L,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[APIKey] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = token
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = companyId
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(2, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = token
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = companyId
        if (__v != 0L) {
          _output__.writeInt64(2, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withToken(__v: _root_.scala.Predef.String): APIKey = copy(token = __v)
    def withCompanyId(__v: _root_.scala.Long): APIKey = copy(companyId = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = token
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = companyId
          if (__t != 0L) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(token)
        case 2 => _root_.scalapb.descriptors.PLong(companyId)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = com.demo.bifrost.token.v1.token.APIKey
}

object APIKey extends scalapb.GeneratedMessageCompanion[com.demo.bifrost.token.v1.token.APIKey] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[com.demo.bifrost.token.v1.token.APIKey] = this
  def merge(`_message__`: com.demo.bifrost.token.v1.token.APIKey, `_input__`: _root_.com.google.protobuf.CodedInputStream): com.demo.bifrost.token.v1.token.APIKey = {
    var __token = `_message__`.token
    var __companyId = `_message__`.companyId
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __token = _input__.readStringRequireUtf8()
        case 16 =>
          __companyId = _input__.readInt64()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder(_message__.unknownFields)
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    com.demo.bifrost.token.v1.token.APIKey(
        token = __token,
        companyId = __companyId,
        unknownFields = if (_unknownFields__ == null) _message__.unknownFields else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[com.demo.bifrost.token.v1.token.APIKey] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      com.demo.bifrost.token.v1.token.APIKey(
        token = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        companyId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Long]).getOrElse(0L)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = TokenProto.javaDescriptor.getMessageTypes.get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = TokenProto.scalaDescriptor.messages(0)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = com.demo.bifrost.token.v1.token.APIKey(
    token = "",
    companyId = 0L
  )
  implicit class APIKeyLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, com.demo.bifrost.token.v1.token.APIKey]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, com.demo.bifrost.token.v1.token.APIKey](_l) {
    def token: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.token)((c_, f_) => c_.copy(token = f_))
    def companyId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.companyId)((c_, f_) => c_.copy(companyId = f_))
  }
  final val TOKEN_FIELD_NUMBER = 1
  final val COMPANY_ID_FIELD_NUMBER = 2
  def of(
    token: _root_.scala.Predef.String,
    companyId: _root_.scala.Long
  ): _root_.com.demo.bifrost.token.v1.token.APIKey = _root_.com.demo.bifrost.token.v1.token.APIKey(
    token,
    companyId
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[demo.bifrost.token.v1.APIKey])
}
