# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: idl/gsc/asgard/health.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "demo.health.Health" do
    optional :name, :string, 1
    optional :status, :enum, 2, "demo.health.HealthStatus"
    optional :reason, :string, 3
  end
  add_enum "demo.health.HealthStatus" do
    value :HEALTH_STATUS_INVALID, 0
    value :HEALTH_STATUS_RED, 10
    value :HEALTH_STATUS_YELLOW, 20
    value :HEALTH_STATUS_GREEN, 30
  end
end

module Demo
  module Health
    Health = Google::Protobuf::DescriptorPool.generated_pool.lookup("demo.health.Health").msgclass
    HealthStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("demo.health.HealthStatus").enummodule
  end
end
