# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: idl/pagination.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "demo.health.RequestPagination" do
    optional :limit, :int32, 1
    optional :offset, :int32, 2
  end
  add_message "demo.health.ResponsePagination" do
    optional :limit, :int32, 1
    optional :offset, :int32, 2
    optional :pages_remaining, :bool, 3
  end
end

module Demo
  module Health
    RequestPagination = Google::Protobuf::DescriptorPool.generated_pool.lookup("demo.health.RequestPagination").msgclass
    ResponsePagination = Google::Protobuf::DescriptorPool.generated_pool.lookup("demo.health.ResponsePagination").msgclass
  end
end
