// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: idl/demo/health/health.proto

package com.demo.health;

public final class HealthProto {
  private HealthProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_health_Health_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_health_Health_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033idl/demo/health/health.proto\022\ndemo.healt" +
      "h\"P\n\006Health\022\014\n\004name\030\001 \001(\t\022(\n\006status\030\002 \001(" +
      "\0162\030.demo.health.HealthStatus\022\016\n\006reason\030\003 " +
      "\001(\t*w\n\014HealthStatus\022\031\n\025HEALTH_STATUS_INV" +
      "ALID\020\000\022\025\n\021HEALTH_STATUS_RED\020\n\022\030\n\024HEALTH_" +
      "STATUS_YELLOW\020\024\022\033\n\023HEALTH_STATUS_GREEN\020\036" +
      "\032\002\010\001B)\n\016com.demo.healthB\013HealthProtoP\001Z\010h" +
      "ealthpbb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_demo_health_Health_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_health_Health_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_health_Health_descriptor,
        new java.lang.String[] { "Name", "Status", "Reason", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}