// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: idl/demo/health/health.proto

package com.demo.health;

/**
 * Protobuf enum {@code demo.health.HealthStatus}
 */
public enum HealthStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>HEALTH_STATUS_INVALID = 0;</code>
   */
  HEALTH_STATUS_INVALID(0),
  /**
   * <code>HEALTH_STATUS_RED = 10;</code>
   */
  HEALTH_STATUS_RED(10),
  /**
   * <code>HEALTH_STATUS_YELLOW = 20;</code>
   */
  HEALTH_STATUS_YELLOW(20),
  /**
   * <code>HEALTH_STATUS_GREEN = 30 [deprecated = true];</code>
   */
  @java.lang.Deprecated
  HEALTH_STATUS_GREEN(30),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>HEALTH_STATUS_INVALID = 0;</code>
   */
  public static final int HEALTH_STATUS_INVALID_VALUE = 0;
  /**
   * <code>HEALTH_STATUS_RED = 10;</code>
   */
  public static final int HEALTH_STATUS_RED_VALUE = 10;
  /**
   * <code>HEALTH_STATUS_YELLOW = 20;</code>
   */
  public static final int HEALTH_STATUS_YELLOW_VALUE = 20;
  /**
   * <code>HEALTH_STATUS_GREEN = 30 [deprecated = true];</code>
   */
  public static final int HEALTH_STATUS_GREEN_VALUE = 30;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static HealthStatus valueOf(int value) {
    return forNumber(value);
  }

  public static HealthStatus forNumber(int value) {
    switch (value) {
      case 0: return HEALTH_STATUS_INVALID;
      case 10: return HEALTH_STATUS_RED;
      case 20: return HEALTH_STATUS_YELLOW;
      case 30: return HEALTH_STATUS_GREEN;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<HealthStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      HealthStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<HealthStatus>() {
          public HealthStatus findValueByNumber(int number) {
            return HealthStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.demo.health.HealthProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final HealthStatus[] VALUES = values();

  public static HealthStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private HealthStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:demo.health.HealthStatus)
}
